import {describe,it,expect} from 'vitest';
import {diagnosticActionIds,catalogDefinitions,parseDiagnosticParameters,validateDiagnosticOutput,interpretDiagnostic,diagnosticDataSchemas} from './diagnostics.js';
import {syntheticDiagnostic} from './diagnostic-fixtures.js';
describe('diagnostic contracts',()=>{
  it.each(diagnosticActionIds)('validates the %s parser',action=>{const sample={...syntheticDiagnostic(action),engine:'PowerShell 7.5.0'};expect(validateDiagnosticOutput(action,sample).actionId).toBe(action);expect(interpretDiagnostic(sample).length).toBeGreaterThan(0);});
  it('defines nine read-only bounded actions',()=>{expect(catalogDefinitions).toHaveLength(9);expect(catalogDefinitions.every(a=>!a.requiresElevation&&a.timeoutMs<=20000&&a.maxOutputBytes<=524288)).toBe(true);});
  it.each(['command','scriptPath','shell','executable','rawArgs','powershellCommand','script','arbitraryArgs'])('rejects forbidden %s parameters',key=>{expect(()=>parseDiagnosticParameters('windows.system.summary',{[key]:'anything'})).toThrow();});
  it.each(['Security','Microsoft-Windows-PowerShell/Operational','../System'])('rejects event log %s',logName=>expect(()=>parseDiagnosticParameters('eventlog.query',{logName,level:'Error',timeWindow:'1h',limit:10})).toThrow());
  it('limits events and time windows',()=>{expect(()=>parseDiagnosticParameters('eventlog.query',{logName:'System',level:'Error',timeWindow:'30d',limit:1000})).toThrow();expect(parseDiagnosticParameters('eventlog.query',{logName:'Application',level:'Warning',timeWindow:'7d',limit:100})).toHaveProperty('limit',100);});
  it('does not accept arbitrary DNS domains or gateway IPs',()=>{expect(()=>parseDiagnosticParameters('network.dns.validate',{domain:'internal.invalid'})).toThrow();expect(()=>parseDiagnosticParameters('network.gateway.validate',{ip:'192.0.2.1'})).toThrow();});
  it('rejects invalid output action, numbers, dates and fields',()=>{const s={...syntheticDiagnostic('windows.system.summary'),engine:'PowerShell 7.5.0'};expect(()=>validateDiagnosticOutput('network.dns.validate',s)).toThrow();expect(()=>validateDiagnosticOutput('windows.system.summary',{...s,extra:true})).toThrow();expect(()=>validateDiagnosticOutput('windows.system.summary',{...s,collectedAt:'invalid'})).toThrow();expect(()=>diagnosticDataSchemas['windows.resource.usage'].parse({cpuPercent:200})).toThrow();});
  it('uses objective disk thresholds and does not imply root cause',()=>{const s=syntheticDiagnostic('windows.resource.usage');expect(interpretDiagnostic(s).find(f=>f.key==='disk')?.severity).toBe('Warning');const d=diagnosticDataSchemas[s.actionId].parse(s.data) as Record<string,unknown>;s.data={...d,driveAvailableBytes:1};expect(interpretDiagnostic(s).find(f=>f.key==='disk')?.severity).toBe('Critical');});
  it('reports unavailable observations as Unknown',()=>{const s=syntheticDiagnostic('windows.system.summary');expect(interpretDiagnostic({...s,availability:'PermissionLimited',data:null})[0]?.severity).toBe('Unknown');});
});
