import { readFile } from "node:fs/promises";
import path from "node:path";
import pino from "pino";
import request from "supertest";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { AppConfig } from "@edy/config";
import { seedDatabase } from "../../../prisma/seed.js";
import { seedPhase4 } from "../../../prisma/seed-phase4.js";
import { seedPhase5 } from "../../../prisma/seed-phase5.js";
import { createApp } from "./app.js";
import type { PrismaClient } from "./generated/prisma/client.js";
import { createAuditRepository } from "./modules/audit/audit-repository.js";
import { resetLoginRateLimitsForTests } from "./modules/auth/auth-routes.js";
import { buildAnalytics } from "./modules/analytics/metrics.js";
import { resolveDateRange } from "./modules/analytics/date-range.js";
import { generateReportRecords, processExportJob } from "./modules/analytics/reports.js";
import { resetExportRateLimitsForTests } from "./modules/analytics/routes.js";
import { testDatabase } from "./test-database.js";

const origin="http://127.0.0.1:5173";
type Client={agent:ReturnType<typeof request.agent>;csrf:string;id:string};
let db:PrismaClient,app:ReturnType<typeof createApp>,admin:Client,technician:Client,viewer:Client;
async function login(username:string):Promise<Client>{const agent=request.agent(app),response=await agent.post('/api/v1/auth/login').set('origin',origin).send({username,password:process.env.DEMO_SEED_PASSWORD});return{agent,csrf:response.body.csrfToken as string,id:response.body.account.id as string}}
function create(client:Client,body:object){return client.agent.post('/api/v1/reports').set('origin',origin).set('x-csrf-token',client.csrf).send(body)}
async function waitFor(id:string){for(let i=0;i<80;i+=1){const job=await db.exportJob.findUniqueOrThrow({where:{id}});if(!['Queued','Running'].includes(job.status))return job;await new Promise(resolve=>setTimeout(resolve,25))}throw new Error('export deadline')}

beforeAll(async()=>{db=await testDatabase();await seedDatabase(db);await seedPhase4(db);await seedPhase5(db);const config:AppConfig={NODE_ENV:'test',API_HOST:'127.0.0.1',API_PORT:8080,WEB_ORIGIN:origin,DATABASE_PROVIDER:'sqlite',DATABASE_URL:'file:test',LOG_LEVEL:'silent',PORTFOLIO_DEMO:true,SESSION_IDLE_MINUTES:30,SESSION_ABSOLUTE_HOURS:12,INTEGRATION_SENTINEL_ENABLED:false,INTEGRATION_SIEM_ENABLED:false,INTEGRATION_ANALYTICS_ENABLED:false,INTEGRATION_TIMEOUT_MS:3000,INTEGRATION_MAX_ATTEMPTS:5,INTEGRATION_BACKOFF_BASE_MS:1000};app=createApp({logger:pino({level:'silent'}),webOrigin:origin,jsonLimit:'64kb',version:'test',checkDatabase:async()=>{},prisma:db,audit:createAuditRepository(db),config});resetLoginRateLimitsForTests();resetExportRateLimitsForTests();admin=await login('demo.admin');technician=await login('demo.technician');viewer=await login('demo.viewer')});
afterAll(async()=>db.$disconnect());

describe.sequential('Phase 6 analytics and reports',()=>{
  it('requires authentication and allows all roles to read real dashboard data',async()=>{expect((await request(app).get('/api/v1/dashboard')).status).toBe(401);for(const client of [admin,technician,viewer])expect((await client.agent.get('/api/v1/dashboard?range=30d')).status).toBe(200)});
  it('calculates overview, support, SLA and security metrics from persisted rows',async()=>{const response=await admin.agent.get('/api/v1/dashboard?range=30d');expect(response.body.overview).toMatchObject({openTickets:6,unassignedTickets:1,openSecurityCases:3,highCriticalSecurityCases:2});expect(response.body.support.ticketsCreated).toBeGreaterThan(0);expect(response.body.sla).toHaveProperty('compliancePercent');expect(response.body.security.bySeverity).toEqual(expect.any(Array))});
  it('returns every required domain without NaN, undefined or decorative values',async()=>{const response=await admin.agent.get('/api/v1/dashboard?range=30d');expect(response.body).toEqual(expect.objectContaining({tickets:expect.any(Object),assets:expect.any(Object),diagnostics:expect.any(Object),knowledge:expect.any(Object),security:expect.any(Object),operations:expect.objectContaining({health:expect.objectContaining({diagnosticsWorker:'Disabled',workerHeartbeatAt:null})})}));expect(JSON.stringify(response.body)).not.toMatch(/NaN|undefined|healthScore|attackCounter/u)});
  it('validates custom ranges and their maximum size',async()=>{expect((await admin.agent.get('/api/v1/dashboard?range=custom&from=2026-08-29&to=2026-08-01')).status).toBe(400);expect((await admin.agent.get('/api/v1/dashboard?range=custom&from=2024-01-01&to=2026-08-01')).status).toBe(400);expect((await admin.agent.get('/api/v1/dashboard?range=custom&from=2026-08-01&to=2026-08-28')).status).toBe(200)});
  it('handles a genuinely empty database without misleading percentages',async()=>{const empty=await testDatabase();try{const value=await buildAnalytics(empty,'00000000-0000-4000-8000-000000000000',resolveDateRange({range:'7d'}));expect(value.overview.openTickets).toBe(0);expect(value.support.slaCompliancePercent).toBeNull();expect(value.sla.compliancePercent).toBeNull();expect(value.tickets.byStatus).toEqual([])}finally{await empty.$disconnect()}});
  it('rejects unknown report types through a strict Zod contract',async()=>expect((await create(admin,{reportType:'UnknownReport',format:'CSV',filters:{range:'30d'}})).status).toBe(400));
  it('denies Viewer audit exports and records only sanitized denial context',async()=>{const response=await create(viewer,{reportType:'AuditSummary',format:'CSV',filters:{range:'30d'}});expect(response.status).toBe(403);expect(await db.auditEvent.count({where:{actorId:viewer.id,action:'report.denied'}})).toBe(1)});
  it('creates and completes a CSV job asynchronously with audit lifecycle',async()=>{const response=await create(admin,{reportType:'TicketReport',format:'CSV',filters:{range:'30d'}});expect(response.status).toBe(202);expect(response.body.status).toBe('Queued');const job=await waitFor(response.body.id as string);expect(job.status).toBe('Succeeded');expect(job.rowCount).toBeGreaterThan(0);expect(await db.auditEvent.count({where:{resourceId:job.id,action:{in:['report.requested','report.succeeded']}}})).toBe(2);const content=await readFile(path.resolve('..','..','storage','exports',job.fileName!),'utf8');expect(content).toContain('ticketCode');expect(content).not.toMatch(/description|solution|email|password|session|token/iu)});
  it('creates a valid minimized JSON analytics envelope',async()=>{const response=await create(admin,{reportType:'SecurityCaseReport',format:'JSON',filters:{range:'30d'}}),job=await waitFor(response.body.id as string);const parsed=JSON.parse(await readFile(path.resolve('..','..','storage','exports',job.fileName!),'utf8')) as Record<string,unknown>;expect(parsed).toMatchObject({schemaVersion:1,source:'edy-helpdesk',dataset:'SecurityCases'});expect(JSON.stringify(parsed)).not.toMatch(/summary|reason|evidenceSnapshot|password|raw/iu)});
  it('applies technician operational scope in report queries',async()=>{const interval=resolveDateRange({range:'30d'}),adminRows=await generateReportRecords(db,'TicketReport','Admin',admin.id,interval),techRows=await generateReportRecords(db,'TicketReport','Technician',technician.id,interval);expect(techRows.length).toBeLessThan(adminRows.length);expect(techRows.every(row=>typeof row.assigneeRef==='string')).toBe(true)});
  it('limits Viewer exports to minimized non-sensitive report types',async()=>{expect((await create(viewer,{reportType:'DiagnosticReport',format:'JSON',filters:{range:'7d'}})).status).toBe(403);expect((await create(viewer,{reportType:'AssetReport',format:'JSON',filters:{range:'7d'}})).status).toBe(202)});
  it('paginates report history and scopes non-admin history to ownership',async()=>{const adminList=await admin.agent.get('/api/v1/reports?page=1&pageSize=2'),viewerList=await viewer.agent.get('/api/v1/reports?page=1&pageSize=100');expect(adminList.status).toBe(200);expect(adminList.body.data).toHaveLength(2);expect(adminList.body.pagination.total).toBeGreaterThanOrEqual(3);expect(viewerList.body.data.every((item:{requestedBy:string})=>item.requestedBy===viewer.id)).toBe(true)});
  it('marks elapsed exports expired and returns 410 instead of a stale file',async()=>{const job=await db.exportJob.create({data:{requestedBy:admin.id,reportType:'TicketReport',format:'CSV',filters:{range:'7d'},status:'Succeeded',expiresAt:new Date(0),fileName:'10000000-0000-4000-8000-000000000001.csv',fileSize:1,rowCount:1}});const response=await admin.agent.get(`/api/v1/reports/${job.id}/download`);expect(response.status).toBe(410);expect((await db.exportJob.findUniqueOrThrow({where:{id:job.id}})).status).toBe('Expired')});
  it('persists a safe failure state when server storage is unavailable',async()=>{const job=await db.exportJob.create({data:{requestedBy:admin.id,reportType:'TicketReport',format:'CSV',filters:{range:'7d'},expiresAt:new Date(Date.now()+86_400_000)}});await processExportJob(db,createAuditRepository(db),path.resolve('package.json'),job.id);const failed=await db.exportJob.findUniqueOrThrow({where:{id:job.id}});expect(failed.status).toBe('Failed');expect(failed.errorCode).toBe('EXPORT_GENERATION_FAILED')});
  it('rate limits report creation after five requests per minute',async()=>{resetExportRateLimitsForTests();for(let index=0;index<5;index+=1)expect((await create(admin,{reportType:'KnowledgeReport',format:'JSON',filters:{range:'today'}})).status).toBe(202);expect((await create(admin,{reportType:'KnowledgeReport',format:'JSON',filters:{range:'today'}})).status).toBe(429)});
});
