import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Activity, BookOpenCheck, Gauge, HardDrive, LifeBuoy, ShieldCheck } from 'lucide-react';
import { BarChart, DateRangeFilter, MetricCard } from '../components/AnalyticsPrimitives';
import { ErrorState, ListSkeleton } from '../components/Feedback';
import { getDashboard, type DateRangeSelection } from '../lib/api';
import { formatTime } from '../i18n/I18nProvider';

type AnalyticsKind='support'|'sla'|'assets'|'diagnostics'|'knowledge'|'security';
const pageMeta:Record<AnalyticsKind,{eyebrow:string;title:string;description:string;icon:typeof Activity}>={
  support:{eyebrow:'Support operations',title:'Support analytics',description:'Ticket flow, service response and workload context without employee scoring.',icon:LifeBuoy},
  sla:{eyebrow:'Service targets',title:'SLA analytics',description:'Current exposure and completed-ticket compliance using persisted SLA clocks.',icon:Gauge},
  assets:{eyebrow:'Endpoint estate',title:'Asset analytics',description:'Inventory distribution and deterministic diagnostic signals from local data.',icon:HardDrive},
  diagnostics:{eyebrow:'Read-only diagnostics',title:'Diagnostic analytics',description:'Execution outcomes and structured findings, never raw command output.',icon:Activity},
  knowledge:{eyebrow:'Support enablement',title:'Knowledge analytics',description:'Publication state and real links between articles and tickets.',icon:BookOpenCheck},
  security:{eyebrow:'Security escalation',title:'Security analytics',description:'Case workload by real severity and lifecycle state. No simulated threat counters.',icon:ShieldCheck},
};

export function AnalyticsPage({kind}:{kind:AnalyticsKind}){
  const [range,setRange]=useState<DateRangeSelection>({range:'30d'});
  const query=useQuery({queryKey:['dashboard',range],queryFn:()=>getDashboard(range)});
  const meta=pageMeta[kind],Icon=meta.icon;
  return <div className="page-stack analytics-page"><header className="page-header"><div><span className="eyebrow eyebrow--accent">{meta.eyebrow}</span><h1>{meta.title}</h1><p>{meta.description}</p></div><DateRangeFilter value={range} onChange={setRange}/></header>{query.isPending?<section className="panel"><ListSkeleton rows={7}/></section>:query.isError?<section className="panel"><ErrorState onRetry={()=>void query.refetch()}/></section>:<><div className="analytics-context"><span><Icon size={15}/>{query.data.mode==='Demo'?'Portfolio Demo · Synthetic data':'Local Operational · Local data'}</span><span>{query.data.range.displayFrom} — {query.data.range.displayTo}</span><span>Updated {formatTime(query.data.generatedAt)}</span></div><AnalyticsContent kind={kind} data={query.data}/></>}</div>;
}

function AnalyticsContent({kind,data}:{kind:AnalyticsKind;data:Awaited<ReturnType<typeof getDashboard>>}){
  if(kind==='support')return <><section className="analytics-metrics"><MetricCard label="Tickets created" value={data.support.ticketsCreated}/><MetricCard label="Resolved" value={data.support.ticketsResolved} tone="success"/><MetricCard label="Closed" value={data.support.ticketsClosed}/><MetricCard label="Avg. resolution" value={data.support.averageResolutionMinutes===null?null:Math.round(data.support.averageResolutionMinutes)} suffix=" min"/><MetricCard label="Avg. first response" value={data.support.averageFirstResponseMinutes===null?null:Math.round(data.support.averageFirstResponseMinutes)} suffix=" min"/><MetricCard label="SLA compliance" value={data.support.slaCompliancePercent} suffix="%" tone="success"/><MetricCard label="Reopened" value={data.support.reopenedTickets} tone="warning"/><MetricCard label="Unassigned" value={data.support.unassignedTickets} tone="warning"/></section><section className="chart-grid"><BarChart title="Tickets by status" description="Current status of tickets created in the selected range." data={data.tickets.byStatus}/><BarChart title="Tickets by priority" description="Priority distribution with labels in addition to color." data={data.tickets.byPriority} tone="secondary"/><BarChart title="Tickets by category" description="Demand grouped by the persisted ticket category." data={data.tickets.byCategory}/><BarChart title="Tickets by department" description="Demand grouped by requester department." data={data.tickets.byDepartment} tone="neutral"/><BarChart title="Operational assignment" description="Work distribution for context; this is not a technician ranking." data={data.tickets.byTechnician} tone="success"/></section><section className="panel technician-panel"><header className="panel__header"><div><span className="section-kicker">Workload context</span><h2>Technician operations</h2></div></header>{data.technicians.length?<div className="technician-grid">{data.technicians.map(item=><article key={item.id}><strong>{item.name}</strong><span>{item.assignedTickets} active assignments</span><small>{item.byStatus.map(state=>`${state.label}: ${state.value}`).join(' · ')||'No active work'}</small></article>)}</div>:<p className="chart-empty">No data available.</p>}</section></>;
  if(kind==='sla')return <><section className="analytics-metrics"><MetricCard label="Within SLA" value={data.sla.withinSla} tone="success"/><MetricCard label="At risk" value={data.sla.atRisk} tone="warning"/><MetricCard label="Breached" value={data.sla.breached} tone="critical"/><MetricCard label="Paused" value={data.sla.paused}/><MetricCard label="Resolved within SLA" value={data.sla.resolvedWithinSla} tone="success"/><MetricCard label="Compliance" value={data.sla.compliancePercent} suffix="%"/></section><section className="chart-grid chart-grid--wide"><BarChart title="SLA state" description="Open-ticket clocks at generation time. Historical breach timestamps are never erased." data={data.sla.distribution}/><article className="panel formula-card"><span className="section-kicker">Formula & clock</span><h2>How this view is calculated</h2><dl><div><dt>Compliance</dt><dd>Resolved within target ÷ resolved tickets with an SLA.</dd></div><div><dt>Pause</dt><dd>Waiting User and configured Waiting Third Party states suspend the clock.</dd></div><div><dt>Stop</dt><dd>The resolution clock stops when the ticket is resolved.</dd></div><div><dt>Reopen</dt><dd>Reopen resumes the preserved clock; recorded breaches remain historical facts.</dd></div><div><dt>Timezone</dt><dd>UI boundaries use America/Sao_Paulo; persisted instants remain UTC.</dd></div></dl></article></section></>;
  if(kind==='assets')return <><section className="analytics-metrics"><MetricCard label="Active assets" value={data.assets.active} tone="success"/><MetricCard label="Maintenance" value={data.assets.maintenance} tone="warning"/><MetricCard label="Retired" value={data.assets.retired}/><MetricCard label="Unassigned" value={data.assets.unassigned}/><MetricCard label="Warning findings" value={data.assets.warningFindings} tone="warning"/><MetricCard label="Critical findings" value={data.assets.criticalFindings} tone="critical"/><MetricCard label="Stale diagnostic data" value={data.assets.staleDiagnosticData}/></section><section className="chart-grid"><BarChart title="Assets by department" description="Active inventory grouped by department." data={data.assets.byDepartment}/><BarChart title="Assets by type" description="Persisted asset types." data={data.assets.byType} tone="secondary"/><BarChart title="Assets by OS" description="Operating system values from inventory; unknown remains explicit." data={data.assets.byOs} tone="neutral"/></section></>;
  if(kind==='diagnostics')return <><section className="analytics-metrics"><MetricCard label="Diagnostic runs" value={data.diagnostics.runs}/><MetricCard label="Succeeded" value={data.diagnostics.succeeded} tone="success"/><MetricCard label="Failed" value={data.diagnostics.failed} tone="critical"/><MetricCard label="Timed out" value={data.diagnostics.timedOut} tone="warning"/><MetricCard label="Cancelled" value={data.diagnostics.cancelled}/></section><section className="chart-grid"><BarChart title="Runs by diagnostic area" description="Catalog categories for jobs requested in the selected range." data={data.diagnostics.byArea}/><BarChart title="Common structured findings" description="Deterministic labels from persisted findings; no root cause is inferred." data={data.diagnostics.commonFindings} tone="warning"/></section></>;
  if(kind==='knowledge')return <><section className="analytics-metrics"><MetricCard label="Published articles" value={data.knowledge.published} tone="success"/><MetricCard label="Draft articles" value={data.knowledge.draft}/><MetricCard label="Archived articles" value={data.knowledge.archived}/><MetricCard label="Articles linked" value={data.knowledge.articlesLinkedToTickets}/><MetricCard label="Tickets with reference" value={data.knowledge.ticketsWithKnowledgeReference}/></section><section className="chart-grid chart-grid--wide"><BarChart title="Most referenced articles" description="Real ticket links; article content is not included in analytics." data={data.knowledge.mostReferenced}/></section></>;
  return <><section className="analytics-metrics"><MetricCard label="Open cases" value={data.security.open}/><MetricCard label="High / critical" value={data.security.highCritical} tone="critical"/><MetricCard label="Unassigned" value={data.security.unassigned} tone="warning"/><MetricCard label="Resolved" value={data.security.resolved} tone="success"/><MetricCard label="False positive" value={data.security.falsePositive}/></section><section className="chart-grid"><BarChart title="Cases by severity" description="Persisted SecurityCase severity for the selected range." data={data.security.bySeverity} tone="warning"/><BarChart title="Cases by status" description="Persisted SecurityCase lifecycle state." data={data.security.byStatus} tone="secondary"/></section></>;
}
