import {useRef,useState,type FormEvent} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,ArrowUpRight,Clock3,Play,RefreshCw,ShieldCheck,StopCircle} from 'lucide-react';
import {Link,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {useAuth} from '../components/Auth';
import {DiagnosticMode,HealthBadge,FindingRow} from '../components/EndpointHealth';
import {ErrorState,ListSkeleton} from '../components/Feedback';
import {ApiError,getAsset} from '../lib/api';
import {getDiagnosticCatalog,getDiagnosticHistory,getDiagnosticJob,requestDiagnostic,cancelDiagnostic,registerLocalEndpoint,diagnosticName,collectedAgo,safeDiagnosticError,type DiagnosticJob} from '../lib/diagnostics';
import {formatDateTime} from '../i18n/I18nProvider';

const date=(v:string)=>formatDateTime(v);
export function DiagnosticsPage(){
  const {id=''}=useParams(),[params,setParams]=useSearchParams(),{session}=useAuth();
  const page=Number(params.get('page'))||1;
  const catalog=useQuery({queryKey:['diagnostic-catalog'],queryFn:getDiagnosticCatalog,refetchInterval:5000});
  const asset=useQuery({queryKey:['asset',id],queryFn:()=>getAsset(id)});
  const history=useQuery({queryKey:['diagnostic-history',id,page],queryFn:()=>getDiagnosticHistory(id,page),refetchInterval:1500});
  const qc=useQueryClient(),navigate=useNavigate();const [error,setError]=useState(''),[pending,setPending]=useState(false);
  const key=useRef<{body:string;key:string}|null>(null);
  const [logName,setLog]=useState('System'),[level,setLevel]=useState('Warning'),[window,setWindow]=useState('24h'),[limit,setLimit]=useState(50);
  const selected=params.get('action')??'windows.system.summary';
  const action=catalog.data?.data.find(a=>a.actionId===selected);
  const canOperate=session?.account.role==='Admin'||session?.account.role==='Technician';
  const active=history.data?.data.find(j=>['Queued','Running'].includes(j.status));
  const canRun=canOperate&&catalog.data?.liveExecutionEnabled&&catalog.data.localAssetId===id&&action?.enabled&&!asset.data?.archivedAt&&!active;
  async function run(e:FormEvent){e.preventDefault();if(!canRun)return;setError('');setPending(true);const parameters=selected==='eventlog.query'?{logName,level,timeWindow:window,limit}:{};const body=JSON.stringify({id,selected,parameters});if(key.current?.body!==body)key.current={body,key:crypto.randomUUID()};try{const j=await requestDiagnostic(id,selected,parameters,key.current.key);key.current=null;await qc.invalidateQueries({queryKey:['diagnostic-history',id]});void navigate(`/diagnostics/jobs/${j.id}`);}catch(e){setError(e instanceof ApiError?(e.detail??e.message):'The diagnostic could not be requested.');}finally{setPending(false);}}
  async function register(){if(!asset.data)return;setPending(true);setError('');try{await registerLocalEndpoint(id,asset.data.version);await qc.invalidateQueries({queryKey:['diagnostic-catalog']});await qc.invalidateQueries({queryKey:['asset',id]});}catch(e){setError(e instanceof ApiError?(e.detail??e.message):'Local registration failed.');}finally{setPending(false);}}
  if(catalog.isPending||asset.isPending)return <ListSkeleton/>;
  if(catalog.isError||asset.isError)return <ErrorState onRetry={()=>{void catalog.refetch();void asset.refetch();}}/>;
  return <div className="page-stack diagnostics-workspace"><header className="page-header"><div><Link className="breadcrumb" to={`/assets/${id}`}><ArrowLeft size={14}/>Endpoint 360</Link><span className="eyebrow eyebrow--accent">Read-only support</span><h1>Local diagnostics</h1><p>{asset.data.assetCode} · {asset.data.hostname||asset.data.name}</p></div><HealthBadge severity={active?.status??'Info'}/></header>
    <DiagnosticMode mode={catalog.data.mode}/>
    {error?<div role="alert" className="inline-alert">{error}<button className="button button--ghost" onClick={()=>{void asset.refetch();void catalog.refetch();setError('');}}>Reload latest state</button></div>:null}
    <div className="diagnostic-layout"><section className="panel diagnostic-request"><header className="panel__header"><div><span className="section-kicker">Explicit execution</span><h2>Run a diagnostic</h2></div><ShieldCheck size={20}/></header>
      <form onSubmit={e=>void run(e)}><label className="field"><span>Approved action</span><select value={selected} onChange={e=>{const next=new URLSearchParams(params);next.set('action',e.target.value);setParams(next);}}>{catalog.data.data.map(a=><option key={a.actionId} value={a.actionId}>{a.name}{a.enabled?'':' · disabled'}</option>)}</select></label><p>{action?.description??'Select an approved catalog action.'}</p>
        {selected==='eventlog.query'?<div className="event-filters"><label className="field"><span>Log</span><select value={logName} onChange={e=>setLog(e.target.value)}><option>System</option><option>Application</option></select></label><label className="field"><span>Level</span><select value={level} onChange={e=>setLevel(e.target.value)}>{['Critical','Error','Warning','Information'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Time range</span><select value={window} onChange={e=>setWindow(e.target.value)}>{['1h','6h','24h','7d'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Record limit</span><input type="number" min={1} max={100} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label></div>:null}
        <div className="execution-contract"><span><ShieldCheck size={14}/>No elevation</span><span><Clock3 size={14}/>{(action?.timeoutMs??0)/1000}s maximum</span><span>Local endpoint only</span></div>
        <button className="button button--primary" disabled={!canRun||pending}><Play size={15}/>{pending?'Requesting…':'Run diagnostic'}</button>
        {!canRun?<p className="diagnostic-hint">{catalog.data.mode==='Demo'?'Live diagnostics disabled in Portfolio Demo. Browse the synthetic history below.':!canOperate?'Your role can view sanitized findings but cannot execute diagnostics.':active?'A check is already active for this endpoint.':catalog.data.localAssetId!==id?'This asset is not registered as the local endpoint.':'The local worker or selected action is unavailable.'}</p>:null}
      </form>
      {catalog.data.mode==='Operational'&&session?.account.role==='Admin'&&catalog.data.localAssetId!==id?<div className="local-registration"><p>Registration authorizes this Windows host only. Asset hostname/IP fields are never used as execution targets.</p><button className="button button--secondary" disabled={pending||catalog.data.workerStatus!=='Ready'} onClick={()=>void register()}>Register Local Endpoint</button></div>:null}
    </section><aside className="panel diagnostic-guidance"><span className="section-kicker">Execution boundary</span><h2>Observe. Validate. Support.</h2><p>Checks collect bounded observations. Findings suggest a support area, not an absolute root cause.</p><ul><li>No command entry or remote target</li><li>Verified scripts and validated JSON</li><li>No restart, reset or remediation</li><li>15-minute freshness window</li></ul><Link className="text-link" to="/knowledge">Open support knowledge<ArrowUpRight size={14}/></Link></aside></div>
    <section className="panel diagnostic-history"><header className="panel__header"><div><span className="section-kicker">Persisted execution trail</span><h2>Diagnostic history</h2></div><button className="button button--ghost" onClick={()=>void history.refetch()} aria-label="Refresh diagnostic history"><RefreshCw size={15}/>Refresh</button></header>
      {history.isPending?<ListSkeleton/>:history.isError?<ErrorState onRetry={()=>void history.refetch()}/>:history.data.data.length?<div>{history.data.data.map(j=><JobRow key={j.id} job={j}/>)}</div>:<div className="mini-empty">No diagnostics yet. No collection starts automatically.</div>}
      {history.data&&history.data.pagination.totalPages>1?<nav className="pagination" aria-label="Diagnostic history pages"><button disabled={page<=1} onClick={()=>{const p=new URLSearchParams(params);p.set('page',String(page-1));setParams(p);}}>Previous</button><span>Page {page} of {history.data.pagination.totalPages}</span><button disabled={page>=history.data.pagination.totalPages} onClick={()=>{const p=new URLSearchParams(params);p.set('page',String(page+1));setParams(p);}}>Next</button></nav>:null}
    </section>
  </div>;
}
function JobRow({job}:{job:DiagnosticJob}){return <Link className="diagnostic-job-row" to={`/diagnostics/jobs/${job.id}`}><div><strong>{diagnosticName(job.actionId)}</strong><span>{job.requestedByName??'Authorized operator'} · {date(job.requestedAt)}</span>{job.result?.findings[0]?<small>{job.result.findings[0].label}: {job.result.findings[0].detail}</small>:null}</div><HealthBadge severity={job.status}/><span>{job.durationMs===null?'—':`${(job.durationMs/1000).toFixed(1)}s`}</span><span>{job.sourceMode==='Demo'?'Synthetic':job.freshness??'—'}</span><ArrowUpRight size={16}/></Link>;}
export function DiagnosticResultPage(){
  const {id=''}=useParams(),[page,setPage]=useState(1),{session}=useAuth(),[error,setError]=useState(''),[cancelling,setCancelling]=useState(false);
  const q=useQuery({queryKey:['diagnostic-job',id,page],queryFn:()=>getDiagnosticJob(id,page),refetchInterval:query=>query.state.data&&['Queued','Running'].includes(query.state.data.status)?1000:30000});
  if(q.isPending)return <ListSkeleton/>;if(q.isError)return <ErrorState onRetry={()=>void q.refetch()}/>;
  const j=q.data,active=['Queued','Running'].includes(j.status),result=j.result;
  async function cancel(){setCancelling(true);try{await cancelDiagnostic(id);await q.refetch();}catch(e){setError(e instanceof ApiError?(e.detail??e.message):'Cancellation could not be requested.');}finally{setCancelling(false);}}
  return <div className="page-stack diagnostic-result"><header className="page-header"><div><Link className="breadcrumb" to={`/assets/${j.assetId}/diagnostics`}><ArrowLeft size={14}/>Diagnostic history</Link><span className="eyebrow eyebrow--accent">{j.sourceMode==='Demo'?'Synthetic snapshot':'Private local observation'}</span><h1>{diagnosticName(j.actionId)}</h1><p>{date(j.requestedAt)} · {j.engine??'Engine selected by worker'}</p></div><HealthBadge severity={j.status}/></header>
    <DiagnosticMode mode={j.sourceMode}/>{error?<div className="inline-alert" role="alert">{error}</div>:null}
    {active?<section className="panel diagnostic-progress" role="status" aria-live="polite"><span className="spinner"/><div><h2>{j.cancelRequestedAt?'Cancelling safely…':j.status==='Queued'?'Waiting for the local worker':'Read-only collection in progress'}</h2><p>The worker owns the deadline, output limits and process-tree cleanup.</p></div>{(session?.account.role==='Admin'||j.requestedBy===session?.account.id)&&session?.account.role!=='Viewer'?<button className="button button--secondary" disabled={cancelling||!!j.cancelRequestedAt} onClick={()=>void cancel()}><StopCircle size={15}/>Cancel diagnostic</button>:null}</section>:null}
    {!active&&j.status!=='Succeeded'?<section className="panel diagnostic-failure" role="alert"><HealthBadge severity={j.status}/><h2>Collection did not produce an accepted result</h2><p>{safeDiagnosticError(j.errorCode)}</p><Link className="button button--secondary" to={`/assets/${j.assetId}/diagnostics?action=${j.actionId}`}>Review and retry</Link></section>:null}
    {result?<><div className="diagnostic-result-meta"><span><Clock3 size={15}/>{collectedAgo(result.collectedAt)}</span><strong title="Fresh: collected within 15 minutes. Historical snapshots are not continuous monitoring.">{j.freshness} data</strong><span>{j.durationMs===null?'—':`${(j.durationMs/1000).toFixed(2)}s`}</span><span>Rule version {result.ruleVersion}</span></div><section className="panel structured-findings"><header className="panel__header"><div><span className="section-kicker">Deterministic interpretation</span><h2>Structured findings</h2></div></header>{result.findings.map(f=><FindingRow key={f.key} finding={f}/>)}</section>
      {j.actionId==='eventlog.query'?<section className="panel event-log-panel"><header className="panel__header"><div><span className="section-kicker">Sanitized · bounded · read-only</span><h2>Windows Event Logs</h2></div><span>{q.data.pagination.total} records retained</span></header>{q.data.events.length?<div className="event-list">{q.data.events.map(e=><details className="event-record" key={e.id}><summary><span><time>{date(e.timestamp)}</time><strong>{e.provider}</strong><small>{e.message.slice(0,140)}</small></span><span>Event ID {e.eventId}</span><HealthBadge severity={e.level==='Error'?'Warning':e.level==='Information'?'Info':e.level}/></summary><p>{e.message}</p></details>)}</div>:<p className="mini-empty">{session?.account.role==='Viewer'?'Event messages are restricted to authorized technicians.':'No matching events retained for this result.'}</p>}{q.data.pagination.totalPages>1?<nav className="pagination" aria-label="Event result pages"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>{page} / {q.data.pagination.totalPages}</span><button disabled={page>=q.data.pagination.totalPages} onClick={()=>setPage(page+1)}>Next</button></nav>:null}</section>:result.payload?<Snapshot payload={result.payload}/>:null}
    </>:!active&&j.status==='Succeeded'?<div className="mini-empty">Detailed results have expired. Minimal job history remains available.</div>:null}
    <footer className="diagnostic-disclaimer">No remediation was executed. Observations may be incomplete or stale. Validate findings in the endpoint context.</footer>
  </div>;
}
function Snapshot({payload}:{payload:unknown}){
  const value=payload as {data?:Record<string,unknown>};if(!value.data)return null;
  const pretty=(key:string)=>key.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,c=>c.toUpperCase());
  function display(v:unknown):string{if(v===null||v===undefined)return 'Not available';if(typeof v==='boolean')return v?'Yes':'No';if(Array.isArray(v))return v.map(display).join(', ');return typeof v==='string'||typeof v==='number'?String(v):'Structured observation';}
  return <section className="panel observation-snapshot"><header className="panel__header"><div><span className="section-kicker">Collected values · immutable snapshot</span><h2>Observation details</h2></div></header>{Object.entries(value.data).map(([key,v])=>Array.isArray(v)&&v.some(x=>typeof x==='object'&&x!==null)?<div className="observation-group" key={key}><h3>{pretty(key)}</h3>{v.map((record,i)=><dl className="observation-grid" key={i}>{Object.entries(record as Record<string,unknown>).map(([k,x])=><div key={k}><dt>{pretty(k)}</dt><dd>{display(x)}</dd></div>)}</dl>)}</div>:<dl className="observation-grid" key={key}><div><dt>{pretty(key)}</dt><dd>{display(v)}</dd></div></dl>)}</section>;
}
