import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { EmptyState, ErrorState, ListSkeleton } from '../components/Feedback';
import { useAuth } from '../components/Auth';
import { ApiError, createTicket, getMetadata, ticketPriorities } from '../lib/api';

export function NewTicketPage() {
  const { session } = useAuth();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const metadata = useQuery({ queryKey: ['metadata'], queryFn: getMetadata });
  const mutation = useMutation({ mutationFn: createTicket });
  const [error, setError] = useState('');

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError('');
    const data = new FormData(event.currentTarget);
    try {
      const ticket = await mutation.mutateAsync({
        title: data.get('title'), description: data.get('description'), requesterId: data.get('requesterId'),
        departmentId: data.get('departmentId') || undefined, categoryId: data.get('categoryId'), priority: data.get('priority'),
        assetId: data.get('assetId') || null,
      });
      await queryClient.invalidateQueries({ queryKey: ['tickets'] });
      void navigate(`/tickets/${ticket.id}`, { state: { message: `${ticket.ticketCode ?? ticket.ticketNumber} created.` } });
    } catch (reason) { setError(reason instanceof ApiError ? reason.detail ?? reason.message : 'Ticket creation failed.'); }
  }

  if (session?.account.role === 'Viewer') return <EmptyState title="Read-only access" description="Viewer sessions can review tickets but cannot create or modify service requests." />;
  if (metadata.isPending) return <ListSkeleton rows={6} />;
  if (metadata.isError || !metadata.data) return <ErrorState title="Ticket form is unavailable." onRetry={() => void metadata.refetch()} />;
  return <div className="page-stack">
    <header className="page-header page-header--compact"><div><Link className="breadcrumb" to="/tickets"><ArrowLeft size={14} />Ticket queue</Link><span className="eyebrow eyebrow--accent">New request</span><h1>Create ticket</h1><p>Capture enough context for accurate triage. The ticket code and SLA are generated by the server.</p></div></header>
    <form className="editor-layout" onSubmit={(event) => void submit(event)}>
      <section className="panel form-panel"><header className="panel__header"><div><span className="section-kicker">Request</span><h2>Service details</h2></div></header>
        {error ? <div className="inline-alert" role="alert">{error}</div> : null}
        <div className="form-grid"><label className="field field--wide"><span>Summary</span><input name="title" required minLength={3} maxLength={200} placeholder="Short, specific description of the issue" autoFocus /></label>
          <label className="field field--wide"><span>Description</span><textarea name="description" required minLength={3} maxLength={10000} rows={8} placeholder="What happened, when it started, and how it affects the requester" /></label>
          <label className="field"><span>Requester</span><select name="requesterId" required defaultValue=""><option value="" disabled>Select requester</option>{metadata.data.requesters.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label>
          <label className="field"><span>Department snapshot</span><select name="departmentId" defaultValue=""><option value="">Requester department</option>{metadata.data.departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
          <label className="field"><span>Category</span><select name="categoryId" required defaultValue=""><option value="" disabled>Select category</option>{metadata.data.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
          <label className="field"><span>Priority</span><select name="priority" defaultValue="Medium">{ticketPriorities.map((item) => <option key={item}>{item}</option>)}</select></label>
          <label className="field field--wide"><span>Related asset <small>Optional</small></span><select name="assetId" defaultValue=""><option value="">No related asset</option>{metadata.data.assets.map((item) => <option key={item.id} value={item.id}>{item.assetTag} · {item.name}</option>)}</select></label>
        </div>
        <footer className="form-actions"><Link className="button button--ghost" to="/tickets">Cancel</Link><button className="button button--primary" type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Creating…' : <>Create ticket<ArrowRight size={15} /></>}</button></footer>
      </section>
      <aside className="panel form-guidance"><CheckCircle2 size={21} /><h2>What happens next</h2><ol><li>A permanent `HD-YYYY-NNNNNN` code is reserved.</li><li>The matching 24×7 SLA policy starts.</li><li>Creation is written to history and append-only audit.</li></ol><p>No diagnostic command runs from this form.</p></aside>
    </form>
  </div>;
}
