import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, ArrowRight, CircleDotDashed, Clock3, Plus, RefreshCw, ShieldCheck, TicketCheck, UserRoundCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { EmptyState, ErrorState, ListSkeleton } from '../components/Feedback';
import { PriorityIndicator, SlaIndicator, StatusChip, TicketCode } from '../components/TicketPrimitives';
import { useAuth } from '../components/Auth';
import { getDashboard, getTickets } from '../lib/api';
import { translateUi } from '../i18n/I18nProvider';

export function OverviewPage() {
  const { session } = useAuth();
  const dashboard=useQuery({queryKey:['dashboard','overview'],queryFn:()=>getDashboard({range:'7d'}),refetchInterval:60_000});
  const recent=useQuery({queryKey:['tickets','overview'],queryFn:()=>getTickets({page:1,pageSize:6,sort:'updatedAt',order:'desc'})});
  const metrics=dashboard.data?.overview;
  return <div className="page-stack page-stack--dense"><header className="page-header"><div><span className="eyebrow eyebrow--accent">Executive operations</span><h1>Service desk pulse</h1><p>Attention, SLA exposure and operational performance derived only from persisted HelpDesk data.</p></div>{session?.account.role !== 'Viewer' ? <Link className="button button--primary" to="/tickets/new"><Plus size={16}/>New ticket</Link> : null}</header>
    <section className="metric-strip overview-metrics" aria-label="Executive service desk metrics"><OverviewMetric label="Open tickets" value={metrics?.openTickets} icon={TicketCheck}/><OverviewMetric label="My tickets" value={metrics?.myTickets} icon={UserRoundCheck}/><OverviewMetric label="Unassigned" value={metrics?.unassignedTickets} icon={CircleDotDashed} tone="warning"/><OverviewMetric label="SLA at risk" value={metrics?.slaAtRisk} icon={Clock3} tone="warning"/><OverviewMetric label="SLA breached" value={metrics?.slaBreached} icon={AlertTriangle} tone="critical"/><OverviewMetric label="Critical tickets" value={metrics?.criticalTickets} icon={AlertTriangle} tone="critical"/></section>
    <div className="overview-grid"><section className="panel panel--flush" aria-labelledby="priority-work-title"><header className="panel__header"><div><span className="section-kicker">Recently updated</span><h2 id="priority-work-title">Priority work</h2></div><Link className="text-link" to="/tickets">View queue <ArrowRight size={14}/></Link></header>{recent.isPending?<ListSkeleton rows={5}/>:recent.isError?<ErrorState onRetry={()=>void recent.refetch()}/>:recent.data?.data.length?<div className="ticket-compact-list">{recent.data.data.map(ticket=><Link className="ticket-compact" to={`/tickets/${ticket.id}`} key={ticket.id}><div><TicketCode ticket={ticket}/><strong>{ticket.title}</strong><span>{ticket.requester.displayName} · {ticket.category.name}</span></div><PriorityIndicator priority={ticket.priority}/><StatusChip status={ticket.status}/><SlaIndicator ticket={ticket} compact/></Link>)}</div>:<EmptyState title="No active tickets yet." description="New service requests will appear here as soon as they are created." action={<Link className="button button--secondary" to="/tickets/new">Create first ticket</Link>}/>}</section>
      <aside className="overview-rail"><section className="panel attention-panel"><header className="panel__header"><div><span className="section-kicker">Triage</span><h2>Attention lane</h2></div></header><div className="attention-panel__body"><span className="attention-orbit"><AlertTriangle size={20}/></span><h3>{translateUi(`${metrics?.slaAtRisk??0} at risk · ${metrics?.slaBreached??0} breached`)}</h3><p>Review time-sensitive work before the next persisted SLA target.</p><Link className="button button--secondary" to="/tickets?slaState=at-risk">Review SLA queue</Link></div></section><section className="panel security-overview-card"><ShieldCheck size={20}/><div><span>Security workload</span><strong>{translateUi(`${metrics?.openSecurityCases??0} open cases`)}</strong><small>{translateUi(`${metrics?.highCriticalSecurityCases??0} high or critical`)}</small></div><Link className="text-link" to="/security">Open security <ArrowRight size={13}/></Link></section></aside>
    </div><section className="overview-footer"><span>{dashboard.data?.mode==='Demo'?'Portfolio Demo · Synthetic data':'Local Operational · Local data'}</span><span>7-day performance window · America/Sao_Paulo</span><button type="button" onClick={()=>{void dashboard.refetch();void recent.refetch()}}><RefreshCw size={13}/>Refresh</button></section></div>;
}
function OverviewMetric({label,value,icon:Icon,tone='accent'}:{label:string;value:number|undefined;icon:typeof TicketCheck;tone?:'accent'|'warning'|'critical'}){return <article className={`metric metric--${tone}`}><span className="metric__icon"><Icon size={17}/></span><span><small>{label}</small><strong>{value??'—'}</strong></span></article>}
