import {z} from 'zod';
import {requestJson} from './api';
import {currentLanguage,formatRelative,translateUi} from '../i18n/I18nProvider';
const finding=z.object({key:z.string(),label:z.string(),severity:z.enum(['Healthy','Info','Warning','Critical','Unknown']),detail:z.string(),recommendation:z.string(),area:z.string()});
export type DiagnosticFinding=z.infer<typeof finding>;
const pagination=z.object({page:z.number(),pageSize:z.number(),total:z.number(),totalPages:z.number()});
const result=z.object({id:z.string(),collectedAt:z.string(),findings:z.array(finding),expiresAt:z.string(),ruleVersion:z.number(),payload:z.unknown().optional()}).passthrough();
export const diagnosticJob=z.object({id:z.string(),actionId:z.string(),assetId:z.string(),requestedBy:z.string(),requestedByName:z.string().optional(),requestedAt:z.string(),startedAt:z.string().nullable(),completedAt:z.string().nullable(),status:z.enum(['Queued','Running','Succeeded','Failed','TimedOut','Cancelled']),durationMs:z.number().nullable(),exitCode:z.number().nullable(),engine:z.string().nullable(),sourceMode:z.enum(['Demo','Operational']),errorCode:z.string().nullable(),cancelRequestedAt:z.string().nullable(),result:result.nullable().optional(),freshness:z.enum(['Fresh','Stale']).optional()}).passthrough();
export type DiagnosticJob=z.infer<typeof diagnosticJob>;
export const getDiagnosticCatalog=()=>requestJson('/api/v1/diagnostics/catalog',z.object({mode:z.enum(['Demo','Operational']),liveExecutionEnabled:z.boolean(),localAssetId:z.string().nullable(),workerStatus:z.string(),data:z.array(z.object({actionId:z.string(),name:z.string(),description:z.string(),category:z.string(),version:z.number(),enabled:z.boolean(),requiresElevation:z.boolean(),timeoutMs:z.number()}))}));
export const getDiagnosticHistory=(assetId:string,page=1,pageSize=10)=>requestJson(`/api/v1/assets/${assetId}/diagnostics?page=${page}&pageSize=${pageSize}`,z.object({mode:z.enum(['Demo','Operational']),data:z.array(diagnosticJob),pagination}));
export const getDiagnosticJob=(id:string,page=1)=>requestJson(`/api/v1/diagnostics/jobs/${id}?page=${page}&pageSize=10`,diagnosticJob.extend({events:z.array(z.object({id:z.string(),timestamp:z.string(),eventId:z.number(),level:z.string(),provider:z.string(),message:z.string()})),pagination}));
export const requestDiagnostic=(id:string,actionId:string,parameters:object,key:string)=>requestJson(`/api/v1/assets/${id}/diagnostics`,diagnosticJob,{method:'POST',headers:{'x-idempotency-key':key},body:{actionId,parameters}});
export const cancelDiagnostic=(id:string)=>requestJson(`/api/v1/diagnostics/jobs/${id}/cancel`,z.object({id:z.string(),cancellationRequested:z.boolean()}),{method:'POST',body:{}});
export const registerLocalEndpoint=(assetId:string,version:number)=>requestJson('/api/v1/diagnostics/local-endpoint',z.object({assetId:z.string(),registeredAt:z.string()}),{method:'POST',body:{assetId,version}});
export function diagnosticName(id:string){return translateUi(({'windows.system.summary':'System summary','windows.resource.usage':'Resource usage','windows.services.important':'Important services','windows.update.status':'Windows Update status','network.ip.configuration':'IP configuration','network.gateway.validate':'Gateway validation','network.dns.validate':'DNS validation','network.route.summary':'Route summary','eventlog.query':'Windows Event Logs'} as Record<string,string>)[id]??'Diagnostic');}
export function collectedAgo(value:string){return `${currentLanguage()==='pt-BR'?'Coletado':'Collected'} ${formatRelative(value)}`;}
export function safeDiagnosticError(code:string|null){const en=({'TIMEOUT':'The bounded collection timed out. No result was accepted.','OUTPUT_LIMIT':'The collection exceeded its output limit and was stopped.','SCRIPT_INTEGRITY_FAILURE':'Script integrity verification failed. Execution was refused.','OUTPUT_VALIDATION_FAILURE':'The response did not match the approved data contract.','AUTHORIZATION_REVOKED':'Permission changed before collection completed.','ELEVATED_CONTEXT_DENIED':'Elevated execution is not permitted.','WORKER_INTERRUPTED':'The worker stopped before this check completed.','CANCELLED':'This diagnostic was cancelled.','PROCESS_FAILED':'The provider could not complete this collection.','ACTION_DISABLED':'This catalog action is no longer enabled.'} as Record<string,string>)[code??'']??'The check could not complete safely. Review the local worker status before retrying.';if(currentLanguage()==='en')return en;return ({'TIMEOUT':'A coleta limitada excedeu o tempo. Nenhum resultado foi aceito.','OUTPUT_LIMIT':'A coleta excedeu o limite de saída e foi interrompida.','SCRIPT_INTEGRITY_FAILURE':'A verificação de integridade do script falhou. A execução foi recusada.','OUTPUT_VALIDATION_FAILURE':'A resposta não corresponde ao contrato de dados aprovado.','AUTHORIZATION_REVOKED':'A permissão mudou antes da conclusão da coleta.','ELEVATED_CONTEXT_DENIED':'A execução elevada não é permitida.','WORKER_INTERRUPTED':'O worker foi interrompido antes da conclusão da verificação.','CANCELLED':'Este diagnóstico foi cancelado.','PROCESS_FAILED':'O provedor não conseguiu concluir esta coleta.','ACTION_DISABLED':'Esta ação do catálogo não está mais habilitada.'} as Record<string,string>)[code??'']??'A verificação não pôde ser concluída com segurança. Revise o status do worker local antes de tentar novamente.';}
